### ISSUE TITLE
GPU resources

### ISSUE THREAD

**Issue by xubin04** [HakamShams/IDEE#1]
I am very interested in this dataset. Could you please share the approximate GPU resources required for the entire training process?

**Comment by HakamShams** [comment]
Thank you for reaching out. The required GPU resources depend on the model and the data (synthetic/real) you want to use. Please check table 19, page 36 in the paper (https://arxiv.org/pdf/2410.24075).
In general, you can train on a single GPU and If you have a limited memory you can use the flag "en_use_checkpoint" in the config file.
